// libs/features/three-houses/src/lib/components/three-houses-form/three-houses-form.component.ts
import {
  Component,
  ChangeDetectionStrategy,
  Output,
  EventEmitter,
} from '@angular/core';
import { FormBuilder } from '@angular/forms';
import { Options } from '@fepmu/data/three-houses';

@Component({
  selector: 'fepmu-three-houses-form',
  templateUrl: './three-houses-form.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ThreeHousesFormComponent {
  @Output()
  public optionsSubmitted = new EventEmitter<Options>();

  public formGroup = this.fb.group({
    route: ['Azure Moon'],
    avatarGender: ['male'],
    randomizeClasses: [{ value: false, disabled: true }],
    allowInviableBuilds: [{ value: false, disabled: true }],
    allowOtherHouses: [{ value: true, disabled: false }],
    balanceRoster: [{ value: false, disabled: true }],
    includeFreeUpdates: [{ value: true, disabled: false }],
    includeSeasonPass: [{ value: false, disabled: true }],
    rosterSize: [{ value: 12, disabled: false }],
  });

  public routes = [
    'Azure Moon',
    'Crimson Flower',
    'Verdant Wind',
    'Silver Snow',
  ];
  public avatarGender = ['male', 'female', 'random'];

  constructor(private fb: FormBuilder) {}

  submitPick() {
    this.optionsSubmitted.emit(this.formGroup.value);
  }
}

<div class="space-y-4">
  <div [formGroup]="formGroup" class="space-y-2">
    <!-- Route -->
    <tui-select formControlName="route" tuiTextfieldSize="m">
      Route
      <tui-data-list-wrapper *tuiDataList [items]="routes"></tui-data-list-wrapper>
    </tui-select>
    <!-- Gender -->
    <tui-select formControlName="avatarGender" tuiTextfieldSize="m">
      Avatar gender
      <tui-data-list-wrapper *tuiDataList [items]="avatarGender"></tui-data-list-wrapper>
    </tui-select>
    <!-- Randomize classes -->
    <tui-checkbox-labeled formControlName="randomizeClasses" size="l">
      Randomize classes
    </tui-checkbox-labeled>
    <!-- Allow inviable builds -->
    <tui-checkbox-labeled formControlName="allowInviableBuilds" size="l">
      Allow inviable builds
    </tui-checkbox-labeled>
    <!-- Allow other houses -->
    <tui-checkbox-labeled formControlName="allowOtherHouses" size="l">
      Allow other houses
    </tui-checkbox-labeled>
    <!-- Balance roster -->
    <tui-checkbox-labeled formControlName="balanceRoster" size="l">
      Balance roster
    </tui-checkbox-labeled>
    <!-- Include free updates -->
    <tui-checkbox-labeled formControlName="includeFreeUpdates" size="l">
      Include free updates
    </tui-checkbox-labeled>
    <!-- Include season pass -->
    <tui-checkbox-labeled formControlName="includeSeasonPass" size="l">
      Include season pass
    </tui-checkbox-labeled>
    <!-- Roster size -->
    <tui-input-count formControlName="rosterSize" tuiTextfieldSize="m" [min]="2" [max]="12">
      Roster size
    </tui-input-count>
  </div>
  <div class="flex">
    <button class="grow" tuiButton type="button" (click)="submitPick()">Pick my units</button>
  </div>
</div>

// libs/features/three-houses/src/components/three-houses-form/three-houses-form.tsx
import {
  Button,
  Checkbox,
  NumberInput,
  NumberInputField,
  NumberInputStepper,
  NumberIncrementStepper,
  NumberDecrementStepper,
  Select,
  FormControl,
  FormLabel,
} from '@chakra-ui/react';
import { Options, defaultOptions } from '@fepmu/data/three-houses';
import { ChangeEvent, useEffect, useState } from 'react';

/* eslint-disable-next-line */
export interface ThreeHousesFormProps {
  onSubmit: (options: Options) => void;
}

export function ThreeHousesForm(props: ThreeHousesFormProps) {
  const { onSubmit } = props;

  const routes = [
    'Azure Moon',
    'Crimson Flower',
    'Verdant Wind',
    'Silver Snow',
  ];
  const avatarGender = ['male', 'female', 'random'];

  const [state, setState] = useState<Options>(defaultOptions);
  useEffect(() => {
    if (!state.randomizeClasses) {
      setState({
        ...state,
        allowInviableBuilds: false,
        balanceRoster: false,
      });
    }
  }, [state.randomizeClasses]);

  const isCheckbox = (
    x: HTMLSelectElement | HTMLInputElement
  ): x is HTMLInputElement => x.type === 'checkbox';

  const handleInputChange = (
    event: ChangeEvent<HTMLInputElement | HTMLSelectElement>
  ) => {
    const target = event.target;
    const value = isCheckbox(target) ? target.checked : target.value;
    const name = target.name;

    setState({
      ...state,
      [name]: value,
    });
  };

  const handleRosterSizeChange = (_: string, size: number) =>
    setState({ ...state, rosterSize: size });

  const formSubmit = () => onSubmit(state);

  return (
    <form>
      <div className="space-y-4">
        <div className="space-y-2 flex flex-col">
          <FormControl>
            <FormLabel htmlFor="route">Route</FormLabel>
            <Select
              value={state.route}
              id="route"
              name="route"
              onChange={handleInputChange}
            >
              {routes.map((item) => (
                <option key={item} value={item}>
                  {item}
                </option>
              ))}
            </Select>
          </FormControl>
          <FormControl>
            <FormLabel htmlFor="avatarGender">Avatar gender</FormLabel>
            <Select
              value={state.avatarGender}
              id="avatarGender"
              name="avatarGender"
              onChange={handleInputChange}
            >
              {avatarGender.map((item) => (
                <option key={item} value={item}>
                  {item}
                </option>
              ))}
            </Select>
          </FormControl>
          <FormControl>
            <Checkbox
              id="randomizeClasses"
              name="randomizeClasses"
              isChecked={state.randomizeClasses}
              onChange={handleInputChange}
            >
              Randomize classes
            </Checkbox>
          </FormControl>
          <FormControl isDisabled={!state.randomizeClasses}>
            <Checkbox
              id="allowInviableBuilds"
              name="allowInviableBuilds"
              isChecked={state.allowInviableBuilds}
              onChange={handleInputChange}
            >
              Allow inviable builds
            </Checkbox>
          </FormControl>
          <FormControl>
            <Checkbox
              id="allowOtherHouses"
              name="allowOtherHouses"
              isChecked={state.allowOtherHouses}
              onChange={handleInputChange}
            >
              Allow other houses
            </Checkbox>
          </FormControl>
          <FormControl isDisabled={!state.randomizeClasses}>
            <Checkbox
              id="balanceRoster"
              name="balanceRoster"
              isChecked={state.balanceRoster}
              onChange={handleInputChange}
            >
              Balance roster
            </Checkbox>
          </FormControl>
          <FormControl>
            <Checkbox
              id="includeFreeUpdates"
              name="includeFreeUpdates"
              isChecked={state.includeFreeUpdates}
              onChange={handleInputChange}
            >
              Include free updates
            </Checkbox>
          </FormControl>
          <FormControl>
            <Checkbox
              id="includeSeasonPass"
              name="includeSeasonPass"
              isChecked={state.includeSeasonPass}
              onChange={handleInputChange}
            >
              Include season pass
            </Checkbox>
          </FormControl>
          <FormControl>
            <FormLabel htmlFor="rosterSize">Roster size</FormLabel>
            <NumberInput
              value={state.rosterSize}
              min={2}
              max={12}
              onChange={handleRosterSizeChange}
            >
              <NumberInputField id="rosterSize" name="rosterSize" />
              <NumberInputStepper>
                <NumberIncrementStepper />
                <NumberDecrementStepper />
              </NumberInputStepper>
            </NumberInput>
          </FormControl>
        </div>
        <div className="flex">
          <Button
            className="grow"
            size={'lg'}
            type="button"
            onClick={formSubmit}
          >
            Pick my units
          </Button>
        </div>
      </div>
    </form>
  );
}

export default ThreeHousesForm;
