// libs/ui/unit-list/src/components/unit/unit.tsx
import { Pick } from '@fepmu/data/three-houses';

/* eslint-disable-next-line */
export interface UnitProps {
  pick: Pick;
}

export function Unit(props: UnitProps) {
  const { unit, class: unitClass } = props.pick;
  return (
    <div className="bg-neutral-50 p-2 rounded-lg">
      <span className="font-bold">{unit.name}</span> {unitClass?.name}
      {}
    </div>
  );
}

export default Unit;

// libs/ui/unit/src/lib/components/unit/unit.component.ts
import {
  Component,
  ViewEncapsulation,
  ChangeDetectionStrategy,
  Input,
} from '@angular/core';
import { Character, CharacterClass } from '@fepmu/data/three-houses';

@Component({
  selector: 'fepmu-unit',
  templateUrl: './unit.component.html',
  encapsulation: ViewEncapsulation.Emulated,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class UnitComponent {
  @Input()
  public unit: Character | undefined;

  @Input()
  public class: CharacterClass | undefined;
}

<div class="bg-neutral-50 p-2 rounded-lg">
  <span class="font-bold">{{ unit?.name }}</span> {{ class?.name }}
</div>
