// libs/ui/unit/src/lib/components/unit-list/unit-list.component.ts
import {
  Component,
  ViewEncapsulation,
  ChangeDetectionStrategy,
  Input,
} from '@angular/core';
import { Pick } from '@fepmu/data/three-houses';

@Component({
  selector: 'fepmu-unit-list',
  templateUrl: './unit-list.component.html',
  encapsulation: ViewEncapsulation.Emulated,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class UnitListComponent {
  @Input()
  public units: Pick[] | null = [];

  @Input()
  public bgColor = 'bg-slate-200';
}

<div *ngIf="units?.length" class="px-2 py-2 rounded-lg" [ngClass]="bgColor">
  <div class="pb-2">
    <ng-content></ng-content>
  </div>
  <div class="flex flex-col space-y-2">
    <fepmu-unit
      *ngFor="let unit of units"
      [unit]="unit.unit"
      [class]="unit.class"
    ></fepmu-unit>
  </div>
</div>

// libs/ui/unit-list/src/components/unit-list/unit-list.tsx
import { Pick } from '@fepmu/data/three-houses';
import Unit from '../unit/unit';

/* eslint-disable-next-line */
export interface UnitListProps {
  picks: Pick[];
  children?: React.ReactNode;
}

export function UnitList(props: UnitListProps) {
  const { picks } = props;

  return (
    <div className="px-2 py-2 rounded-lg bg-slate-500">
      <div className="pb-2">{props.children}</div>
      <div className="flex flex-col space-y-2">
        {picks.map((pick) => (
          <Unit key={pick.unit.id} pick={pick} />
        ))}
      </div>
    </div>
  );
}

export default UnitList;
