// libs/features/three-houses/src/lib/containers/three-houses-container/three-houses-container.component.ts
import { Component, ChangeDetectionStrategy } from '@angular/core';
import { Options } from '@fepmu/data/three-houses';

import { ThreeHousesStore } from './three-houses.store';

@Component({
  selector: 'fepmu-three-houses-container',
  templateUrl: './three-houses-container.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [ThreeHousesStore],
})
export class ThreeHousesContainerComponent {
  public selectedUnits = this.store.selected$.asObservable();
  // public availableUnits = this.store.available$;
  // public unavailableUnits = this.store.unavailable$;

  constructor(private store: ThreeHousesStore) {}

  public pickUnits(options: Options) {
    this.store.pickUnits(options);
  }

  public copyToClipboard() {
    this.store.copyToClipboard();
  }
}

<div class="p-4 flex flex-col space-y-4 md:w-3/5 lg:w-2/5 md:mx-auto">
  <fepmu-three-houses-form
    (optionsSubmitted)="pickUnits($event)"
  ></fepmu-three-houses-form>
  <fepmu-unit-list [units]="selectedUnits | async">
    Selected units
  </fepmu-unit-list>
  <!-- <fepmu-unit-list [units]="availableUnits | async">
    Avalaible units
  </fepmu-unit-list>
  <fepmu-unit-list [units]="unavailableUnits | async" [bgColor]="'bg-red-200'">
    Unavailable units
  </fepmu-unit-list> -->
  <div class="flex" *ngIf="(selectedUnits | async)?.length">
    <button class="grow" tuiButton type="button" (click)="copyToClipboard()">
      Copy to clipboard
    </button>
  </div>
</div>

// libs/ui/react/features/three-houses/src/containers/three-houses-container/three-houses-container.tsx
import { Pick, mockPicks } from '@fepmu/data/three-houses';
import { UnitList } from '@fepmu/ui/react/unit-list';
import { useState } from 'react';
import ThreeHousesForm from '../../components/three-houses-form/three-houses-form';

import styles from './three-houses-container.module.scss';

/* eslint-disable-next-line */
export interface ThreeHousesContainerProps {}

export interface State {
  picks: Pick[];
}

export function ThreeHousesContainer(props: ThreeHousesContainerProps) {
  const [state] = useState<State>({
    picks: mockPicks,
  });
  const { picks } = state;

  return (
    <div className="p-4 flex flex-col space-y-4 md:w-3/5 lg:w-2/5 md:mx-auto">
      <ThreeHousesForm />
      <UnitList picks={picks}>Selected units</UnitList>
      {picks.length > 0 ? (
        <div className="flex">
          <button className="grow" type="button">
            Copy to clipboard
          </button>
        </div>
      ) : (
        <></>
      )}
    </div>
  );
}

export default ThreeHousesContainer;
