// libs/features/three-houses/src/containers/three-houses-container/three-houses-container.tsx
import {
  Pick,
  Options,
  applyFilters,
  getUnitsText,
} from '@fepmu/data/three-houses';
import { UnitList } from '@fepmu/ui/unit-list';
import { useEffect, useState } from 'react';
import ThreeHousesForm from '../../components/three-houses-form/three-houses-form';
import { Button } from '@chakra-ui/react';

const createText = (picks: Pick[], route: string) =>
  ['Fire Emblem Three Houses PMU', route, '', getUnitsText(picks)].join('\n');

/* eslint-disable-next-line */
export interface ThreeHousesContainerProps {}

export function ThreeHousesContainer(props: ThreeHousesContainerProps) {
  const [options, setOptions] = useState<Options | undefined>(undefined);
  const [picks, setPicks] = useState<Pick[]>([]);
  const [text, setText] = useState<string>('');

  useEffect(() => {
    if (options) setPicks(applyFilters(options));
  }, [options]);

  useEffect(() => {
    if (picks.length && options) setText(createText(picks, options.route));
  }, [picks]);

  const handleSubmit = (options: Options) => setOptions({...options});

  const copyToClipboard = () => navigator.clipboard.writeText(text).then();

  return (
    <div className="p-4 flex flex-col space-y-4 md:w-3/5 lg:w-2/5 md:mx-auto">
      <ThreeHousesForm onSubmit={handleSubmit} />
      {picks.length > 0 ? (
        <>
          <UnitList picks={picks}>Selected units</UnitList>
          <div className="flex">
            <Button className="grow" size={'lg'} onClick={copyToClipboard}>
              Copy to clipboard
            </Button>
          </div>
        </>
      ) : (
        <></>
      )}
    </div>
  );
}

export default ThreeHousesContainer;

// libs/features/three-houses/src/lib/containers/three-houses-container/three-houses-container.component.ts
import { Component, ChangeDetectionStrategy } from '@angular/core';
import { Options } from '@fepmu/data/three-houses';

import { ThreeHousesStore } from './three-houses.store';

@Component({
  selector: 'fepmu-three-houses-container',
  templateUrl: './three-houses-container.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [ThreeHousesStore],
})
export class ThreeHousesContainerComponent {
  public selectedUnits = this.store.selected$.asObservable();
  // public availableUnits = this.store.available$;
  // public unavailableUnits = this.store.unavailable$;

  constructor(private store: ThreeHousesStore) {}

  public pickUnits(options: Options) {
    this.store.pickUnits(options);
  }

  public copyToClipboard() {
    this.store.copyToClipboard();
  }
}

<div class="p-4 flex flex-col space-y-4 md:w-3/5 lg:w-2/5 md:mx-auto">
  <fepmu-three-houses-form
    (optionsSubmitted)="pickUnits($event)"
  ></fepmu-three-houses-form>
  <fepmu-unit-list [units]="selectedUnits | async">
    Selected units
  </fepmu-unit-list>
  <!-- <fepmu-unit-list [units]="availableUnits | async">
    Avalaible units
  </fepmu-unit-list>
  <fepmu-unit-list [units]="unavailableUnits | async" [bgColor]="'bg-red-200'">
    Unavailable units
  </fepmu-unit-list> -->
  <div class="flex" *ngIf="(selectedUnits | async)?.length">
    <button class="grow" tuiButton type="button" (click)="copyToClipboard()">
      Copy to clipboard
    </button>
  </div>
</div>
